# Generated by Django 4.2.5 on 2023-09-07 05:18

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pass_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passbox',
            name='pass_code',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
